WhiteLagoon.Web/Controllers/BookingController.cs
using System.Globalization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using Syncfusion.DocIORenderer;
using Syncfusion.Drawing;
using Syncfusion.Pdf;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Utility;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Repository;

namespace WhiteLagoon.Web.Controllers
{
    public class BookingController : Controller
    {
        public readonly IUnitOfWork _unitOfWork;
        public readonly IWebHostEnvironment _hostEnvironment;

        public BookingController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult FinalizeBooking(int villaId, DateOnly checkInDate, int nights)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ApplicationUser user = _unitOfWork.User.Get(u => u.Id == userId);

            Booking booking = new()
            {
                VillaId = villaId,
                Villa = _unitOfWork.Villa.Get(u => u.Id==villaId, includeProperties:"VillaAmenity"),
                CheckInDate = checkInDate,
                Nights = nights,
                CheckOutDate = checkInDate.AddDays(nights), //proč toto nefunguje v kookingdetails.cshtml a FinalizeBooking.cshtml - jak naformatovat checkindate aby to fungovalo (lokální formátování)
                UserId = userId,
                Phone = user.PhoneNumber,
                Email = user.Email,
                Name = user.Name,
            };
            booking.TotalCost = booking.Villa.Price * nights;
            return View(booking);
        }
       
        [Authorize]
        [HttpPost]
        public IActionResult FinalizeBooking(Booking booking)
        {
            var villa = _unitOfWork.Villa.Get(u => u.Id == booking.VillaId);

            booking.TotalCost = villa.Price * booking.Nights;

            booking.Status = SD.StatusPending;
            booking.BookingDate = DateTime.Now; //DateTime.Now; - nefunguje - už funguje

            //check available villa numbers - doublecheck
            var villaNumberList = _unitOfWork.VillaNumber.GetAll().ToList();
            var bookedVillas = _unitOfWork.Booking.GetAll(u => u.Status == SD.StatusApproved || u.Status == SD.StatusCheckedIn).ToList();

            int roomsAvailable = SD.VillaRoomsAvailable_Count(villa, booking.CheckInDate, villaNumberList, booking.Nights, bookedVillas);

            if (roomsAvailable == 0)
            {
                TempData["Error"] = "Error: No rooms available for the selected dates";
                return RedirectToAction(nameof(FinalizeBooking), new
                {
                    villaId = booking.VillaId,
                    checkInDate = booking.CheckInDate,
                    nights = booking.Nights
                });
            }
            
            _unitOfWork.Booking.Add(booking);
            _unitOfWork.Save();

            //stripe payment
            var domain = Request.Scheme+"://"+Request.Host.Value+"/";
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = domain + $"booking/BookingConfirmation?bookingId={booking.Id}",
                CancelUrl = domain + $"booking/FinalizeBooking?villaId={booking.VillaId}& checkInDate={booking.CheckInDate}&nights={booking.Nights}",
            };

            options.LineItems.Add(new SessionLineItemOptions
            {
                PriceData = new SessionLineItemPriceDataOptions
                {
                    UnitAmount = (long)booking.TotalCost * 100,
                    Currency = "usd",
                    ProductData = new SessionLineItemPriceDataProductDataOptions
                    {
                        Name = villa.Name,
                        //Images = new List<string> { villa.ImageUrl }
                    },
                },
                Quantity = 1,
            });

            var service = new SessionService();
            Session session = service.Create(options);

            _unitOfWork.Booking.UpdateStripePaymentId(booking.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
            //stripe payment

            //return RedirectToAction(nameof(BookingConfirmation), new { bookingId = booking.Id}); - nefunguje resp. není třeba
        }

        [Authorize]
        public IActionResult BookingConfirmation(int bookingId) //nefunguje zjistit co je špatně - funguje
        {
            Booking bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == bookingId, includeProperties:"User, Villa");

            if (bookingFromDb.Status == SD.StatusPending)
            {
                //pending order we need to confirm if payment is successeful;
                var service = new SessionService();
                Session session = service.Get(bookingFromDb.StripeSessionId);

                if (session.PaymentStatus == "paid")
                {
                    _unitOfWork.Booking.UpdateStatus(bookingFromDb.Id, SD.StatusApproved, 0);
                    _unitOfWork.Booking.UpdateStripePaymentId(bookingFromDb.Id, session.Id, session.PaymentIntentId);
                    _unitOfWork.Save();
                }
                //else
                //{
                //    bookingFromDb.Status = SD.StatusCancelled;
                //}
            }
            return View(bookingId);
        }

        [Authorize]
        public IActionResult BookingDetails(int bookingId)
        {
            Booking bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == bookingId, includeProperties: "User, Villa");

            if (bookingFromDb.VillaNumber == 0 && bookingFromDb.Status == SD.StatusApproved)
            {
                var availableVillaNumber = AssignAvailableVillaNumbersByVilla(bookingFromDb.VillaId);

                bookingFromDb.VillaNumbers = _unitOfWork.VillaNumber.GetAll(u =>
                    u.VillaId == bookingFromDb.VillaId && availableVillaNumber.Any(v => v == u.Villa_Number)).ToList();
            }

            return View(bookingFromDb);
        }

        [HttpPost]
        [Authorize]
        public IActionResult GenerateInvoice(int Id, string downloadType)
        {
            string basePath = _hostEnvironment.WebRootPath;
            
            WordDocument document = new WordDocument();
            
            //Loading the template document
            string dataPath = basePath + @"/exports/BookingDetails.docx";
            using FileStream fileStream = new (dataPath, FileMode.Open, FileAccess.Read,FileShare.ReadWrite);
            document.Open(fileStream, FormatType.Automatic);
            
            //update the template document
            Booking bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == Id, includeProperties: "User, Villa");
            
            //update name
            TextSelection textSelection = document.Find("xx_customer_name", false, true);
            WTextRange textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.Name;

            //update phone
            textSelection = document.Find("xx_customer_phone", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.Phone;

            //update email
            textSelection = document.Find("xx_customer_email", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.Email;

            //update booking number
            textSelection = document.Find("XX_BOOKING_NUMBER", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = "BOOKING NR. - " + bookingFromDb.Id.ToString();

            //update booking Date
            textSelection = document.Find("XX_BOOKING_DATE", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = "BOOKING DATE - " + bookingFromDb.BookingDate.ToShortDateString();

            //update payment Date
            textSelection = document.Find("xx_payment_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.PaymentDate.ToShortDateString();

            //update CheckIn Date
            textSelection = document.Find("xx_checkin_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.CheckInDate.ToShortDateString();

            //update CheckOut Date
            textSelection = document.Find("xx_checkout_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.CheckOutDate.ToShortDateString();

            //update Billing Total
            textSelection = document.Find("xx_booking_total", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = bookingFromDb.TotalCost.ToString("C");

            WTable table = new (document);
            table.TableFormat.Borders.LineWidth = 1F;
            table.TableFormat.BackColor = Color.Black;
            table.TableFormat.Paddings.Top = 7f;
            table.TableFormat.Paddings.Bottom = 7f;
            table.TableFormat.Borders.Horizontal.LineWidth = 1F;
            
            //Adding a new row to the table
            int rows = bookingFromDb.VillaNumber > 0 ? 3 : 2;

WhiteLagoon.Web/Views/Booking/BookingConfirmation.cshtml
@model int

<div class="container  pt-4">
    <div class="col-12 text-center">
        <h1 class="text-success text-center">Your Vacation is Confirmed!</h1>
        Your Order Number is : @Model <br />
        <p>You can view all order details in Manage Order Section.</p>
        <img src="~/images/orderConfirmed.jpg" style="border-radius:20px" width="65%" />
    </div>
    <div class="col-12 text-center text-warning">
        <p class="pt-1">Pack your bags! You are one step closer to an amazing vacation!</p>
    </div>

</div> 

WhiteLagoon.Web/Views/Booking/BookingDetails.cshtml
@model Booking

<div class="p-4 mt-0 mt-lg-4">
    <div class="row" style="border: 1px solid #aaa;">

        <div class="col-12 col-lg-6 p-4 2 mt-2 mt-md-0">
            <div class="row p-1 " style="border-radius:20px; ">
                <div class="col-6">
                    <h3 class="text-success">Villa Details</h3>
                </div>
                <div class="col-6 text-end">
                    <a class="btn btn-secondary my-2" asp-controller="Booking" asp-action="Index"><i class="bi bi-arrow-left-circle"></i> Back to Bookings</a>
                </div>
                <hr />
                <partial name="_VillaDetail" model="@Model.Villa" />
                <hr />
                <div class="text-end">
                    <h4 class="text-danger font-weight-bold ">
                        Booking Total :
                        <span style="border-bottom:1px solid #ff6a00">
                            @Model.TotalCost.ToString("C")
                        </span>
                    </h4>
                </div>

                <hr/>

                <form method="post">
                    <div class="row pt-1 mb-3" style="border-radius:20px">
                        <div class="col-12 text-center">

                            <button type="submit" asp-controller="Booking" asp-action="GenerateInvoice" asp-route-id="@Model.Id" asp-route-downloadType="word" type="submit" class="btn btn-sm btn-secondary my-1">
                                <i class="bi bi-file-earmark-word"></i>Generate invoice - docx
                            </button>

                            <button type="submit" asp-controller="Booking" asp-action="GenerateInvoice" asp-route-id="@Model.Id" asp-route-downloadType="pdf" type="submit" class="btn btn-sm btn-secondary my-1">
                                <i class="bi bi-file-earmark-pdf"></i>Generate invoice - pdf
                            </button>

                        </div>
                    </div>
                </form>

            </div>
        </div>
        <div class="col-12 col-lg-6 p-4 2 mt-4 mt-md-0" style="border-left:1px solid #aaa">
            <form method="post">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="VillaId" />
                @* <input type="hidden" asp-for="VillaNumber" /> *@
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="CheckInDate" />
                <input type="hidden" asp-for="CheckOutDate" />
                <input type="hidden" asp-for="Nights" />
                <div class="row pt-1 mb-3 " style="border-radius:20px; ">
                    <div class="col-6">
                        <h3 class="text-success">Enter Booking Details</h3>
                    </div>
                    <div class="col-6">
                        @if ((Model.Status == SD.StatusPending || Model.Status == SD.StatusApproved) && User.IsInRole(SD.Role_Admin))
                        {
                            <button type="submit" asp-controller="Booking" asp-action="CancelBooking" class="btn btn-sm btn-outline-danger form-control my-1"><i class="bi bi-x-circle"></i> &nbsp; Cancel Booking</button>
                        }
                    </div>
                </div>
                <div class="row">
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Name</label>
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Phone</label>
                        <input asp-for="Phone" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Email</label>
                        <input asp-for="Email" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">No. of nights</label>
                        <input asp-for="Nights" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Status</label>
                        <input asp-for="Status" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Booking Date</label>
                        <input asp-for="BookingDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Check-in Date</label>
                        <input asp-for="CheckInDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Actual Check-in Date</label>
                        <input asp-for="ActualCheckInDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-danger">Check-out Date</label>
                        <input asp-for="CheckOutDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Actual Check-out Date</label>
                        <input asp-for="ActualCheckOutDate" disabled class="form-control" />
                    </div>
                    @if (Model.Status == SD.StatusApproved && User.IsInRole(SD.Role_Admin))
                    {
                        <div class="form-group pt-2 col-6">
                            <label class="text-danger" asp-for="VillaNumber"></label>
                            <select asp-for="VillaNumber" class="form-control">
                                @foreach (var item in Model.VillaNumbers)
                                {
                                    <option value="@item.Villa_Number">@item.Villa_Number</option>
                                }
                            </select>
                        </div>
                    }
                    else
                    {
                        <input type="hidden" asp-for="VillaNumber" />
                        if (Model.Status == SD.StatusCompleted || Model.Status == SD.StatusCheckedIn)
                        {
                            <div class="form-group pt-2 col-6">
                                <label class="text-warning">Villa Number</label>
                                <input asp-for="VillaNumber" disabled class="form-control" />
                            </div>
                        }
                    }
                        @if (Model.IsPaymentSuccessful && User.IsInRole(SD.Role_Admin))
                        {
                            <div class="form-group pt-2 col-6">
                                <label class="text-warning">Stripe PaymentIntent Id</label>
                                <input asp-for="StripePaymentIntentId" disabled class="form-control" />
                            </div>
                            <div class="form-group pt-2 col-6">
                                <label class="text-warning">Stripe Session Id</label>
                                <input asp-for="StripeSessionId" disabled class="form-control" />
                            </div>
                            <div class="form-group pt-2 col-6">
                                <label class="text-warning">Payment Date</label>
                                <input asp-for="PaymentDate" disabled class="form-control" />
                            </div>
                        }
                    </div>
                    <div class="form-group pt-2 pt-md-4">
                            @if (User.IsInRole(SD.Role_Admin))
                            {
                                if (Model.Status == SD.StatusApproved)
                                {
                                <button type="submit" asp-controller="Booking" asp-action="CheckIn" class="btn btn-warning form-control my-1"><i class="bi bi-check2-square"></i> &nbsp; Check In</button>
                                }
                                else if (Model.Status == SD.StatusCheckedIn)
                                {
                            <button type="submit" asp-controller="Booking" asp-action="CheckOut" class="btn btn-success form-control my-1"><i class="bi bi-clipboard2-check"></i> &nbsp; Check Out / Complete Booking</button>
                                }
                            }
                    </div>
                </form>
            </div>
        </div>
    </div>

WhiteLagoon.Web/Views/Booking/FinalizeBooking.cshtml
@model Booking

<div class="container pt-4 mt-0 mt-lg-4">
    <div class="row" style="border: 1px solid #aaa;">

        <div class="col-12 col-lg-7 p-4 2 mt-4 mt-md-0">
            <div class="row p-1 my-1 " style="border-radius:20px; ">
                <div class="col-6">
                    <h3 class="text-success">Villa Details</h3>
                </div>
                <div class="text-end col-6 ">
                    <a asp-controller="Home" asp-action="Index" class="btn btn-sm btn-outline-danger" style="width:200px;">
                        <i class="bi bi-arrow-left-square"></i> &nbsp; Modify Selection
                    </a>
                </div>
                <hr />
                <partial name="_VillaDetail" model="Model.Villa" />
                <hr />
                <div class="text-end">
                    <h4 class="text-danger font-weight-bold ">
                        Booking Total :
                        <span style="border-bottom:1px solid #ff6a00">
                            @Model.TotalCost.ToString("c")
                        </span>
                    </h4>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-5 p-4 2 mt-4 mt-md-0" style="border-left:1px solid #aaa">
            <form method="post">
                <input type="hidden" asp-for="VillaId" />
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="CheckInDate" />
                <input type="hidden" asp-for="CheckOutDate" />
                <input type="hidden" asp-for="Nights" />

                <div class="row pt-1 mb-3 " style="border-radius: 20px;">
                    <div class="col-12">
                        <h3 class="text-success">Enter Booking Details</h3>
                    </div>
                </div>

                <div class="form-group pt-0">
                    <label asp-for="Name" class="text-warning">Name</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group pt-2">
                    <label asp-for="Phone" class="text-warning">Phone</label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group pt-2">
                    <label asp-for="Email" class="text-warning">Email</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group pt-2">
                    <label asp-for="CheckInDate" class="text-warning">Check in Date</label>
                    <input asp-for="CheckInDate" disabled class="form-control" />
                </div>
                <div class="form-group pt-2">
                    <label asp-for="CheckOutDate" class="text-warning">Check Out Date</label>
                    <input asp-for="CheckOutDate" disabled class="form-control" />
                </div>
                <div class="form-group pt-2">
                    <label asp-for="Nights" class="text-warning">No. of nights</label>
                    <input asp-for="Nights" disabled class="form-control" />
                </div>
                <div class="form-group pt-2 pt-md-4">
                    @if (Model.Villa.IsAvailable)
                    {
                        <button type="submit" class="btn btn-success form-control">Looks Good! Checkout Now</button>
                    }
                    else
                    {
                        <input class="btn btn-danger disabled form-control" value="Sold Out" />
                    }

                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WhiteLagoon.Web/Views/Booking/Index.cshtml
@{
    var status = Context.Request.Query["status"];

    var approved = "";
    var pending = "";
    var cancelled = "";
    var checkedIn = "";
    var completed = "";
    var refunded = "";

    switch (status)
    {
        case SD.StatusApproved:
            approved = "text-white bg-success";
            break;
        case SD.StatusPending:
            pending = "text-white bg-success";
            break;
        case SD.StatusCancelled:
            cancelled = "text-white bg-success";
            break;
        case SD.StatusCheckedIn:
            checkedIn = "text-white bg-success";
            break;
        case SD.StatusCompleted:
            completed = "text-white bg-success";
            break;
        case SD.StatusRefunded:
            refunded = "text-white bg-success";
            break;
        default:
            break;
    }
}

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Booking list</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="d-flex justify-content-end pb-4 pt-2">
            <ul class="list-group list-group-horizontal-sm">
                <a style="text-decoration: none;" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusPending">
                <li class="list-group-item @pending">
                        @SD.StatusPending
                </li>
                </a>
                <a style="text-decoration: none;" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusApproved">
                <li class="list-group-item @approved">
                        @SD.StatusApproved
                </li>
                </a>
                <a style="text-decoration: none;" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusCancelled">
                <li class="list-group-item @cancelled">
                        @SD.StatusCancelled
                </li>
                </a>
                <a style="text-decoration: none;" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusCheckedIn">
                <li class="list-group-item @checkedIn">
                        @SD.StatusCheckedIn
                </li>
                </a>
                <a style="text-decoration: none;" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusCompleted">
                <li class="list-group-item @completed">
                        @SD.StatusCompleted
                </li>
                </a>
                <a style="text-decoration: none;" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusRefunded">
                <li class="list-group-item @refunded">
                        @SD.StatusRefunded
                </li>
                </a>
            </ul>
        </div>

        <table id="tblBookings" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Status</th>
                <th>Check In Date</th>
                <th>Nights</th>
                <th>Total</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


@section Scripts {
    <script src="~/js/booking.js"></script>
}