WhiteLagoon.Web/Controllers/VillaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;

namespace WhiteLagoon.Web.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            var villas = _unitOfWork.Villa.GetAll();
            return View(villas);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Villa obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "Name and Description cannot be the same");
            }
            if (ModelState.IsValid)
            {
                if (obj.Image != null)
                {
                    string imageName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_hostEnvironment.WebRootPath, @"images\VillaImages");

                    using var fileStream = new FileStream(Path.Combine(imagePath, imageName), FileMode.Create);

                    obj.Image.CopyTo(fileStream);
                    obj.ImageUrl = @"\images\VillaImages\" + imageName;
                    
                }
                else
                {
                    obj.ImageUrl = "https://placehold.co/600x400";
                }

                _unitOfWork.Villa.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Villa created successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Villa could not be created";
            return View();
        }

        public IActionResult Update(int? villaId)
        {
            Villa? obj = _unitOfWork.Villa.Get(u => u.Id == villaId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Update(Villa obj)
        {
            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("name", "Name and Description cannot be the same");
            }
            if (ModelState.IsValid && obj.Id > 0)
            {
                if (obj.Image != null)
                {
                    string imageName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_hostEnvironment.WebRootPath, @"images\VillaImages");

                    if (!string.IsNullOrEmpty(obj.ImageUrl))
                    {
                        string imageOldPath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));

                        if (System.IO.File.Exists(imageOldPath))
                        {
                            System.IO.File.Delete(imageOldPath);
                        }
                    }

                    using var fileStream = new FileStream(Path.Combine(imagePath, imageName), FileMode.Create);

                    obj.Image.CopyTo(fileStream);
                    obj.ImageUrl = @"\images\VillaImages\" + imageName;
                }
                _unitOfWork.Villa.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Villa updated successfully";
                return RedirectToAction(nameof(Index));
            }
            //TempData["error"] = "Villa could not be updated";
            return View();
        }

        public IActionResult Delete(int? villaId)
        {
            Villa? obj = _unitOfWork.Villa.Get(u => u.Id == villaId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }

        [HttpPost]
        public IActionResult Delete(Villa obj)
        {
            Villa? objFromDb = _unitOfWork.Villa.Get(u => u.Id == obj.Id);
            if (objFromDb is not null)
            {
                if (!string.IsNullOrEmpty(objFromDb.ImageUrl))
                {
                    string imageOldPath = Path.Combine(_hostEnvironment.WebRootPath, objFromDb.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(imageOldPath))
                    {
                        System.IO.File.Delete(imageOldPath);
                    }
                }

                _unitOfWork.Villa.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Villa deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Villa could not be deleted/found";
            return View();
        }
    }
}

WhiteLagoon.Web/Views/Villa/Create.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" class="form-control border shadow" /> 
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Price" class="form-control border shadow" /> 
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Sqft" class="form-control border shadow" /> 
                    <label asp-for="Sqft" class="ms-2"></label>
                    <span asp-validation-for="Sqft" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Occupancy" class="form-control border shadow" />
                    <label asp-for="Occupancy" class="ms-2"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="ImageUrl" hidden class="form-control border shadow" />
                    <input asp-for="Image" class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="ms-2"></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle">Create</i>
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle">Cancel</i>                            
                        </a>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

@section Scripts {
    <Partial name="_ValidationScriptsPartial"/>
}

WhiteLagoon.Web/Views/Villa/Delete.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden/>
            <div class="col-10">
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" disabled class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" disabled class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Price" disabled class="form-control border shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Sqft" disabled class="form-control border shadow" />
                    <label asp-for="Sqft" class="ms-2"></label>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Occupancy" disabled class="form-control border shadow" />
                    <label asp-for="Occupancy" class="ms-2"></label>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="ImageUrl" disabled class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="ms-2"></label>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class="bi bi-trash-fill">Delete</i>
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle">Cancel</i>
                        </a>
                    </div>
                </div>
            </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%" style="border-radius: 5px; border: 1px; color: #bbb9b9" />
            </div>
        </form>

    </div>
</div>

@section Scripts {
    <Partial name="_ValidationScriptsPartial" />
}

WhiteLagoon.Web/Views/Villa/Index.cshtml
@model IEnumerable<WhiteLagoon.Domain.Entities.Villa>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa list</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary"><i class="bi bi-plus-circle"></i>Create new Villa</a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Sqft</th>
                    <th>Occupancy</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Name</td>
                        <td>@obj.Price</td>
                        <td>@obj.Sqft</td>
                        <td>@obj.Occupancy</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Villa" asp-action="Update" asp-route-villaId="@obj.Id" class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square">Edit</i>
                                </a>
                                <a asp-controller="Villa" asp-action="Delete" asp-route-villaId="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill">Delete</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

WhiteLagoon.Web/Views/Villa/Update.cshtml
@model Villa

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="col-10">
                <div class="p-3">
                    @* <div asp-validation-summary="ModelOnly" class="text-danger"></div> *@
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Name" class="form-control border shadow" />
                        <label asp-for="Name" class="ms-2"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Description" class="form-control border shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Price" class="form-control border shadow" />
                        <label asp-for="Price" class="ms-2"></label>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Sqft" class="form-control border shadow" />
                        <label asp-for="Sqft" class="ms-2"></label>
                        <span asp-validation-for="Sqft" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Occupancy" class="form-control border shadow" />
                        <label asp-for="Occupancy" class="ms-2"></label>
                        <span asp-validation-for="Occupancy" class="text-danger"></span>
                    </div>
                    <div class="form-floating py-1 col-12">
                        <input asp-for="Image" class="form-control border shadow" />
                        <input asp-for="ImageUrl" hidden="" class="form-control border shadow" />
                        <label asp-for="ImageUrl" class="ms-2"></label>
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class="bi bi-check-circle">Update</i>
                            </button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle">Cancel</i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%" style="border-radius: 5px; border: 1px; color: #bbb9b9"/>
            </div>
            
        </form>

    </div>
</div>

@section Scripts
{
    <Partial name="_ValidationScriptsPartial" />
}